### ISSUE TITLE
Reason for this tool vs writing Unit Tests

### ISSUE THREAD

**Issue by StephenOTT** [viadee/vPAV#40]
Hey

Great looking tool.

What are the motivations of using this vs writing unit tests for the individual processes?  Are you trying to reduce the number of tests that someone writes / possibly remove the need for a "analyst" to write tests?

**Comment by fkoehne** [comment]
Thanks for your interest!

Technically, the tool _is_ a (giant) reusable unit test.

This yields two important improvements over the individual approach (besides making it easier):
- You have a "common understanding" of the quality aspects you want to check for, esp. when you are maintaining multiple processes (as most of us do).
- We (as a community) can invest far more energy into checkers to investigate inconsistencies suh as  naming conventions, process-to-java consistency or data flow consistency than any individual project could.

This tool does not replace unit tests however, since we can only investigate general aspects of process / java consistency here.

Does this answer your question?

**Comment by fkoehne** [comment]
Well - it probably is answered.
