### ISSUE TITLE
Missing the 'check' goal of vPAV-Maven-Plugin

### ISSUE THREAD

**Issue by Gemba69** [viadee/vPAV#6]
Hello, 

we are a project team of the university of applied science in muenster and actually we try to build a continuous delivery pipeline for a campunda-bpmn project.

We integrated the vPAV Maven Plugin in a special parent pom and used the 'check' goal of the vPAV-Plugin. With the new version 2.2.3 we miss this goal and can't execute the plugin on the way we want to execute it. 

I saw that you removed the BpmnCheckerMojo.java. Is there a special reason for removing this Mojo and the function to execute the plugin via a pom?

kind regards,
Benni

**Comment by sdibernardo** [comment]
Hello Benni,

as of now, we decided to stop supporting the integration of vPAV as Maven Plugin due to several difficulties. For this very reason the mentioned class BpmnCheckerMojo.java has also been removed.

We will keep the development as plugin in mind, but for now we opted to pursue the integration via JUnit.

If you want to automatically check your models for inconsistencies or errors in a CI/CD pipeline, you can easily do this as a JUnit test and execute via e.g. Jenkins or Travis. 

I hope you can continue your work and we appreciate your feedback.

Best regards,
Sascha

**Comment by fkoehne** [comment]
Benni - please let us know, how this works out for you.

**Comment by Gemba69** [comment]
Hello, 

thank you for your replies. 

The big disadvantage of implementing the vPAV-Validation as a JUnit Test is that we have to implement this in every bpmn-process. Our project is focused on a general process-independet pipeline so we want to check every process without implementing a special JUnit Test for the vPav-Validation.

We have cloned your github project and added a customized version to our local infrastructure with the mojo. This plugin is integrated in a special parent pom. This way works for us now.

kind regards,
Benni

**Comment by fkoehne** [comment]
Thanks, all right, in a production setting, we would expect the process to be unit-tested anyway (and we need the unit test run to find spring beans anyway), which is not helping you here. However, why not generalize a JUnit test for your purposes? :)

Best regards,
 Frank
