### ISSUE TITLE
Report broken when no issues have been found

### ISSUE THREAD

**Issue by sebastiansirch** [viadee/vPAV#71]
When no validation errors have been found, the bpmn_validation.js file is not created and hence a JS error is thrown when opening the report. 

Expected behavior: report should work even if no issues have been found (one might want to have a look at the successful checks)

**Comment by fkoehne** [comment]
@sebastiansirch - Since Sascha is a victim of the summer flu: What you requested is actually the designed behaviour we already had. But since we look at erroneous processes a lot, the feature seems to have a bug not discovered so far. We will look into it in the next couple of days. 

BTW: The next release is planned to contain the new java-bytecode-intrepretation features which are kind of complex - time scheduling for releases is difficult right now.

**Comment by sdibernardo** [comment]
Will look into this :)

**Comment by sdibernardo** [comment]
This is done and should be fixed with the next release. Thanks for reporting :)
