### ISSUE TITLE
Fix outdated dependencies with sec issues

### ISSUE THREAD

**Issue by fkoehne** [viadee/vPAV#98]
One or more dependencies were identified with known vulnerabilities in viadee Process Application Validator:
slf4j-api-1.7.12.jar (cpe:/a:slf4j:slf4j:1.7.12, org.slf4j:slf4j-api:1.7.12) : CVE-2018-8088
guava-18.0.jar (cpe:/a:google:guava:18.0, com.google.guava:guava:18.0) : CVE-2018-10237
slf4j-simple-1.7.5.jar (org.slf4j:slf4j-simple:1.7.5, cpe:/a:slf4j:slf4j:1.7.5) : CVE-2018-8088

**Comment by cl-a-us** [comment]
@slf4j-api: according to my investigations, CVE-2018-8088 is a false-positive. (see: https://github.com/qos-ch/slf4j/commit/d2b27fba88e983f921558da27fc29b5f5d269405#diff-eff7c92216930aa8a2c012174eb3e909)
CVE-2018-8088 is a vulnerability due to a de-serialization problem in the constructor of the class EventData which is (as far as I know) not part of the sfl4j-api.
@guava-18: comes with soot: updating soot to 3.3.0 does not fix this *medium* vulnerability.

Nevertheless we should keep the dependencies up to date.

**Comment by fkoehne** [comment]
Nice - maybe we should think about the threshold value in the pom then?
